name: Spring Boot CI/CD to Public & Private Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean bootJar -x test
        
      - name: Copy JAR to Public Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_HOST }}
          username: root
          key: ${{ secrets.PUBLIC_SSH_KEY }}
          source: "build/libs/*SNAPSHOT.jar"
          target: "/root/app/app.jar"

      - name: Deploy JAR to Private from Public
        run: |
          set -x
          ssh ${{ secrets.PUBLIC_USER }}@${{ secrets.PUBLIC_HOST }} << 'EOF'
            mkdir -p /root/app
            scp -o StrictHostKeyChecking=no /root/app/app.jar root@10.10.20.6:/root/app/app.jar
            ssh -o StrictHostKeyChecking=no root@10.10.20.6 "bash /root/deploy.sh"
          EOF



