name: Spring Boot CI/CD to Public & Private Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Deploy to Public Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_HOST }}
          username: root
          key: ${{ secrets.PUBLIC_SSH_KEY }}
          script: |
            mkdir -p /root/app
            cp spring-boot-app/build/libs/*SNAPSHOT.jar /root/app/app.jar
            chmod +x /root/app/deploy_private.sh
            /root/app/deploy_private.sh